version: "3.8"
services:
  flask-app:
    build: ./flask-app
    container_name: flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  db:
    build: ./db
    image: mysql_database
    container_name: mysql
    